server:
  port: 8011
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 3
    instance-info-replication-interval-seconds: 2
    registry-fetch-interval-seconds: 1
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${random.value}